#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Secrets land in .env.local — .gitignore already covers it, and `vercel dev`
# reads it for local runs.
ENV_FILE=".env.local"

REPO="dmalmq/homepage"
DOMAIN="homepage.malmqvist.dev"
CNAME_TARGET="cname.vercel-dns.com"

# The Vercel CLI isn't a dependency of this project, so go through npx.
vercel_cli() { npx --yes vercel "$@"; }

# linked is true once `vercel link` has actually written its marker file.
linked() { [[ -f .vercel/project.json ]]; }

# vercel_env NAME VALUE sets NAME across all three Vercel environments,
# removing any existing value first so re-runs don't collide.
#
# `vercel env add` output is deliberately NOT silenced. It prompts when it can't
# tell which project it's targeting, and hiding stderr turns that question into
# a hang with nothing on screen to explain it.
vercel_env() {
  local name="$1" value="$2" target
  if ! linked; then
    warn "not linked to a Vercel project, so $name wasn't pushed there"
    note "it is saved in $ENV_FILE, so nothing is lost"
    SKIPPED+=("Vercel env $name — run 'npx vercel link', then re-run this script")
    return 0
  fi
  for target in production preview development; do
    vercel_cli env rm "$name" "$target" --yes >/dev/null 2>&1 || true
    if printf '%s' "$value" | vercel_cli env add "$name" "$target"; then
      printf '  %s✓ set%s %s in Vercel (%s)\n' "$GREEN" "$RESET" "$name" "$target"
    else
      SKIPPED+=("Vercel env $name ($target) — add it under Project → Settings → Environment Variables")
      warn "could not set $name for $target"
    fi
  done
}

banner "homepage.malmqvist.dev setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Push the code to GitHub"
say "Vercel builds from GitHub, so the branch has to be pushed before anything"
say "downstream will work."
if [[ -n "$(git status --porcelain 2>/dev/null || true)" ]]; then
  warn "There are uncommitted changes:"
  git status --short | sed 's/^/    /'
  confirm "Push anyway? (uncommitted work stays local)" \
    || { say "Commit them first, then re-run this script."; exit 1; }
fi
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)
say "Pushing $BRANCH to origin…"
git push -u origin "$BRANCH" || { warn "push failed — resolve it and re-run"; exit 1; }
note "origin: $(git remote get-url origin)"
pause "Pushed. Ready to create the Vercel project?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the Vercel project"
say "Vercel auto-detects public/ as static hosting and each file in api/ as a"
say "serverless function. There is no build step to configure."
open_url "https://vercel.com/new"
step "Pick the '$REPO' repository and click Import."
step "Leave every build setting at its default."
step "Don't add environment variables yet — later stages do that for you."
step "Click Deploy."
note "This first deploy will build fine but won't log in yet: the database and"
note "secrets aren't attached. That's expected."
pause "Project created?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Connect the Vercel CLI"
say "Linking this folder to the project lets the next stages set environment"
say "variables directly, so no secret has to be pasted into a browser."
say ""
say "If you're not signed in, a browser window will open for login."
vercel_cli login || true
vercel_cli link || true

# Check the result rather than the exit code: a cancelled link can still exit 0,
# and an unlinked folder makes every later `vercel env` call sit on a prompt.
if linked; then
  say "Linked."
else
  warn "Not linked — .vercel/project.json was not created."
  say "Later stages will still save your secrets to $ENV_FILE, but can't push"
  say "them to Vercel. Run 'npx vercel link' here and re-run this script — it"
  say "remembers the values you already entered."
  SKIPPED+=("vercel link — run 'npx vercel link' in this folder")
fi
pause "Continue?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Attach a Postgres database"
say "The app keeps all of its state in a single Postgres row. Vercel injects"
say "the connection string into the project, so there is nothing to copy here."
open_url "https://vercel.com/dashboard"
step "Open the project → Storage tab."
step "Create a Postgres database and connect it to this project."
note "Vercel's storage section is a marketplace now — the Postgres options are"
note "Neon and Supabase. Either is fine; the app only needs POSTGRES_URL."
say ""
say "The 'state' table is created automatically on first login, so schema.sql"
say "is reference only — you don't need to run it."
pause "Database connected?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Set APP_PASSWORD"
say "This is the single password that unlocks the page. Make it long: it's the"
say "only thing between the internet and your notes."
ask_secret APP_PASSWORD "Choose a password:"
if [[ -z "${APP_PASSWORD:-}" ]]; then
  warn "empty password, skipping"
  SKIPPED+=("APP_PASSWORD — set it before the site will let you in")
else
  write_env APP_PASSWORD "$APP_PASSWORD"
  vercel_env APP_PASSWORD "$APP_PASSWORD"
fi
pause "Ready for the cookie secret?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Generate APP_SECRET"
say "This signs the session cookie. It's generated here so it never has to be"
say "typed or pasted anywhere."
say ""
say "Worth knowing: if it's missing, logins appear to succeed and then fail"
say "silently. That's the single most confusing failure this app has."
APP_SECRET=$(node -e 'process.stdout.write(require("crypto").randomBytes(48).toString("base64url"))' 2>/dev/null \
  || openssl rand -base64 48 2>/dev/null | tr -d '\n' \
  || true)
if [[ -z "${APP_SECRET:-}" ]]; then
  warn "couldn't generate one — no node or openssl on PATH"
  ask_secret APP_SECRET "Paste a long random string:"
fi
note "generated ${#APP_SECRET} characters"
write_env APP_SECRET "$APP_SECRET"
vercel_env APP_SECRET "$APP_SECRET"
pause "Ready to deploy?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Deploy to production"
say "Environment variables only apply to builds made after they were set, so"
say "the project needs one more deploy now that both are in place."
if confirm "Deploy to production now?"; then
  vercel_cli --prod || {
    warn "deploy failed"
    SKIPPED+=("production deploy — run 'npx vercel --prod'")
  }
else
  SKIPPED+=("production deploy — run 'npx vercel --prod'")
  note "skipped"
fi
pause "Ready to attach the domain?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Point $DOMAIN at the project"
say "malmqvist.dev already runs on Vercel behind Cloudflare, so this subdomain"
say "just follows the same pattern."
open_url "https://vercel.com/dashboard"
step "Project → Settings → Domains → add:  $DOMAIN"
pause "Added in Vercel?"
say ""
open_url "https://dash.cloudflare.com"
step "malmqvist.dev → DNS → Records → Add record:"
step "    Type: CNAME    Name: homepage    Target: $CNAME_TARGET"
step "Match the proxy setting your apex record already uses."
step "Then SSL/TLS → Overview → set the encryption mode to 'Full (strict)'."
warn "'Flexible' sends it into an infinite redirect loop through Vercel."
pause "DNS and SSL set?"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Verify it's actually live"
say "Checking the deployment rather than assuming. DNS may need a minute."
say ""
HEALTH_OUT=$(mktemp)
say "GET https://$DOMAIN/api/health"
if curl -fsS --max-time 20 "https://$DOMAIN/api/health" > "$HEALTH_OUT" 2>/dev/null; then
  sed 's/^/    /' "$HEALTH_OUT"
  printf '\n'
  if grep -q '"passwordConfigured":true' "$HEALTH_OUT"; then say "APP_PASSWORD is set."
  else warn "APP_PASSWORD missing — you won't be able to log in."; fi
  if grep -q '"secretConfigured":true' "$HEALTH_OUT"; then say "APP_SECRET is set."
  else warn "APP_SECRET missing — sessions will fail silently."; fi
  if grep -q '"db":"ok"' "$HEALTH_OUT"; then say "Database reachable."
  else warn "Database not reachable — check Storage is connected to the project."; fi
else
  warn "Couldn't reach https://$DOMAIN/api/health"
  note "If DNS is still propagating, give it a minute and re-run this script;"
  note "it remembers the values you already saved."
fi
rm -f "$HEALTH_OUT"
say ""
if curl -fsS -o /dev/null --max-time 20 "https://$DOMAIN/" 2>/dev/null; then
  say "The page itself is serving."
else
  warn "https://$DOMAIN/ isn't serving yet."
fi

finish
say "Open it:      https://$DOMAIN"
say "Then set that URL as your browser's new-tab page."
printf '\n'
